server:
  port: 3355

spring:
  application:
    name: config-client   
  
eureka:
  client:
    register-with-eureka: true  
    fetchRegistry: true         
    service-url:
      defaultZone: http://localhost:7001/eureka    

  instance:
    instance-id: config-client3355
    prefer-ip-address: true                 
   
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities
