client:
  info: version-3
 
spring:
  application:
    name: config-client   
  
eureka:
  client:
    register-with-eureka: true  
    fetchRegistry: true         
    service-url:
      defaultZone: http://localhost:7001/eureka    
